import type { SwarmMode, Vertical } from '../contracts/domain.js';
import type { JobType } from '../contracts/job.js';

export type AutomationVertical = Vertical | 'both';
export type AutomationCategory = 'content' | 'seo' | 'social' | 'data' | 'analytics' | 'media' | 'notification' | 'admin';
export type AutomationRiskLevel = 'low' | 'medium' | 'high';

export interface AutomationDefinition {
  key: string;
  label: string;
  description: string;
  trigger: string;
  category: AutomationCategory;
  vertical: AutomationVertical;
  jobType: JobType;
  defaultMode: SwarmMode;
  enabledByDefault: boolean;
  requiresApproval: boolean;
  supportsAutoMode: boolean;
  riskLevel: AutomationRiskLevel;
  adminGroup: string;
  output: string;
}

export const AUTOMATION_DEFINITIONS: AutomationDefinition[] = [
  {
    key: 'fight.publish.blogDraft',
    label: 'Fight publish → blog draft',
    description: 'Create a reviewable fight preview blog draft whenever a combat fight is published.',
    trigger: 'fight.published',
    category: 'content',
    vertical: 'combat',
    jobType: 'content.fight-publish-blog-draft',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight publishing',
    output: 'Blog draft artifact',
  },
  {
    key: 'fight.publish.twitterPost',
    label: 'Fight publish → Twitter/X post',
    description: 'Create a social post draft for a newly published fight.',
    trigger: 'fight.published',
    category: 'social',
    vertical: 'combat',
    jobType: 'social.fight-publish-post',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Fight publishing',
    output: 'Social draft artifact',
  },
  {
    key: 'fight.publish.seoMetadata',
    label: 'Fight publish → SEO metadata',
    description: 'Generate title, description, OpenGraph, Twitter card, and keyword recommendations for a published fight.',
    trigger: 'fight.published',
    category: 'seo',
    vertical: 'combat',
    jobType: 'seo.metadata',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight publishing',
    output: 'SEO metadata package',
  },
  {
    key: 'fight.publish.schemaMarkup',
    label: 'Fight publish → schema markup',
    description: 'Prepare structured data for fight/event content after publication.',
    trigger: 'fight.published',
    category: 'seo',
    vertical: 'combat',
    jobType: 'seo.schema-markup',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight publishing',
    output: 'Schema markup artifact',
  },
  {
    key: 'fight.publish.sitemapRefresh',
    label: 'Fight publish → sitemap refresh',
    description: 'Create a sitemap refresh instruction after new fight-related URLs are published.',
    trigger: 'fight.published',
    category: 'seo',
    vertical: 'combat',
    jobType: 'seo.sitemap-refresh',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: false,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Fight publishing',
    output: 'Sitemap refresh plan',
  },
  {
    key: 'fight.publish.internalLinks',
    label: 'Fight publish → internal links',
    description: 'Suggest internal links from blogs, fighters, contests, and event pages.',
    trigger: 'fight.published',
    category: 'seo',
    vertical: 'combat',
    jobType: 'seo.internal-links',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight publishing',
    output: 'Internal-linking plan',
  },
  {
    key: 'fight.publish.newsletterDraft',
    label: 'Fight publish → email/newsletter draft',
    description: 'Create a newsletter draft for new fight/event content.',
    trigger: 'fight.published',
    category: 'content',
    vertical: 'combat',
    jobType: 'content.newsletter-draft',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight publishing',
    output: 'Newsletter draft artifact',
  },
  {
    key: 'fight.result.recapBlog',
    label: 'Fight result update → recap blog',
    description: 'Create a fight-result recap blog draft after result data changes.',
    trigger: 'fight.result.updated',
    category: 'content',
    vertical: 'combat',
    jobType: 'content.fight-result-recap',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight results',
    output: 'Recap blog draft',
  },
  {
    key: 'fight.result.socialPost',
    label: 'Fight result update → social result post',
    description: 'Create a social post draft for final fight results.',
    trigger: 'fight.result.updated',
    category: 'social',
    vertical: 'combat',
    jobType: 'social.result-post',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Fight results',
    output: 'Result social draft',
  },
  {
    key: 'fight.result.leaderboardSummary',
    label: 'Fight result update → leaderboard summary',
    description: 'Create a leaderboard summary artifact for admin publishing after fight results are settled.',
    trigger: 'fight.result.updated',
    category: 'analytics',
    vertical: 'combat',
    jobType: 'analytics.leaderboard-summary',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fight results',
    output: 'Leaderboard summary artifact',
  },
  {
    key: 'event.upcoming.previewBlog',
    label: 'Upcoming event → event preview blog',
    description: 'Create a preview blog draft for upcoming events.',
    trigger: 'event.upcoming.detected',
    category: 'content',
    vertical: 'both',
    jobType: 'content.upcoming-event-preview',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Upcoming events',
    output: 'Event preview draft',
  },
  {
    key: 'event.upcoming.fightCardArticle',
    label: 'Upcoming event → fight-card article',
    description: 'Create a full fight-card article draft for upcoming events.',
    trigger: 'event.upcoming.detected',
    category: 'content',
    vertical: 'combat',
    jobType: 'content.fight-card-article',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Upcoming events',
    output: 'Fight-card article draft',
  },
  {
    key: 'event.upcoming.promotionalSocial',
    label: 'Upcoming event → promotional social posts',
    description: 'Create a multi-post promotional campaign draft for upcoming events.',
    trigger: 'event.upcoming.detected',
    category: 'social',
    vertical: 'both',
    jobType: 'social.event-promotional-posts',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Upcoming events',
    output: 'Social campaign draft',
  },
  {
    key: 'event.upcoming.homepageFeature',
    label: 'Upcoming event → homepage featured content',
    description: 'Create homepage feature copy for an upcoming event.',
    trigger: 'event.upcoming.detected',
    category: 'content',
    vertical: 'both',
    jobType: 'content.homepage-feature',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Upcoming events',
    output: 'Homepage feature copy',
  },
  {
    key: 'fighter.added.profileContent',
    label: 'Fighter added → profile content',
    description: 'Create fighter profile copy and SEO fields when a fighter is added.',
    trigger: 'fighter.added',
    category: 'content',
    vertical: 'combat',
    jobType: 'content.fighter-profile',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fighters',
    output: 'Fighter profile draft',
  },
  {
    key: 'fighter.updated.seoRefresh',
    label: 'Fighter updated → SEO refresh',
    description: 'Refresh SEO recommendations when fighter data changes.',
    trigger: 'fighter.updated',
    category: 'seo',
    vertical: 'combat',
    jobType: 'seo.fighter-refresh',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fighters',
    output: 'Fighter SEO refresh package',
  },
  {
    key: 'fighter.recordChanged.contentSuggestion',
    label: 'Fighter record change → content update suggestion',
    description: 'Suggest profile or blog updates after a fighter record changes.',
    trigger: 'fighter.record.changed',
    category: 'content',
    vertical: 'combat',
    jobType: 'content.fighter-update-suggestion',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Fighters',
    output: 'Content update suggestion',
  },
  {
    key: 'wrestling.matchPublished.previewBlog',
    label: 'Pro-wrestling match publish → match preview blog',
    description: 'Create a match preview blog draft after a wrestling match is published.',
    trigger: 'wrestling.match.published',
    category: 'content',
    vertical: 'pro_wrestling',
    jobType: 'content.pro-wrestling-match-preview',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Pro wrestling matches',
    output: 'Wrestling preview blog draft',
  },
  {
    key: 'wrestling.resultUpdated.recapBlog',
    label: 'Pro-wrestling result update → match recap blog',
    description: 'Create a wrestling match recap blog draft after result update.',
    trigger: 'wrestling.result.updated',
    category: 'content',
    vertical: 'pro_wrestling',
    jobType: 'content.pro-wrestling-result-recap',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Pro wrestling matches',
    output: 'Wrestling recap blog draft',
  },
  {
    key: 'wrestler.added.profileContent',
    label: 'Wrestler added → wrestler profile content',
    description: 'Create wrestler profile content and SEO metadata when a wrestler is added.',
    trigger: 'wrestler.added',
    category: 'content',
    vertical: 'pro_wrestling',
    jobType: 'content.wrestler-profile',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Wrestlers',
    output: 'Wrestler profile draft',
  },
  {
    key: 'contest.created.rulesExplainer',
    label: 'Contest created → rules/explainer content',
    description: 'Create rules and how-to-play copy for a newly created contest.',
    trigger: 'contest.created',
    category: 'content',
    vertical: 'both',
    jobType: 'content.contest-rules-explainer',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Contests',
    output: 'Contest explainer draft',
  },
  {
    key: 'contest.closingSoon.reminderPost',
    label: 'Contest closing soon → reminder post',
    description: 'Create a social reminder draft before contest lock time.',
    trigger: 'contest.closing_soon',
    category: 'social',
    vertical: 'both',
    jobType: 'social.contest-reminder',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Contests',
    output: 'Contest reminder social draft',
  },
  {
    key: 'contest.completed.winnersAnnouncement',
    label: 'Contest completed → winners announcement',
    description: 'Create winners announcement copy after contest completion.',
    trigger: 'contest.completed',
    category: 'social',
    vertical: 'both',
    jobType: 'social.winners-announcement',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Contests',
    output: 'Winners announcement draft',
  },
  {
    key: 'blog.approved.twitterPost',
    label: 'Blog approved → Twitter/X post',
    description: 'Create a social post draft when a blog is approved.',
    trigger: 'blog.approved',
    category: 'social',
    vertical: 'both',
    jobType: 'social.blog-approved-post',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Blogs',
    output: 'Blog social draft',
  },
  {
    key: 'blog.approved.seoAudit',
    label: 'Blog approved → SEO audit',
    description: 'Audit blog SEO after approval.',
    trigger: 'blog.approved',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.blog-audit',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Blogs',
    output: 'Blog SEO audit',
  },
  {
    key: 'blog.approved.relatedLinks',
    label: 'Blog approved → related-post linking',
    description: 'Suggest related post links after blog approval.',
    trigger: 'blog.approved',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.related-post-linking',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Blogs',
    output: 'Related-linking plan',
  },
  {
    key: 'blog.approved.imagePrompt',
    label: 'Blog approved → image prompt generation',
    description: 'Create safe image-generation prompts for approved blog artwork.',
    trigger: 'blog.approved',
    category: 'media',
    vertical: 'both',
    jobType: 'media.image-prompt',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Blogs',
    output: 'Image prompt artifact',
  },
  {
    key: 'blog.approved.newsletterDraft',
    label: 'Blog approved → newsletter draft',
    description: 'Create newsletter copy after blog approval.',
    trigger: 'blog.approved',
    category: 'content',
    vertical: 'both',
    jobType: 'content.blog-newsletter-draft',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Blogs',
    output: 'Blog newsletter draft',
  },
  {
    key: 'seo.dailyAudit',
    label: 'Daily SEO audit',
    description: 'Run a daily SEO audit job for configured website areas.',
    trigger: 'schedule.daily',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.daily-audit',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Scheduled SEO',
    output: 'Daily SEO audit',
  },
  {
    key: 'seo.weeklyTrafficOpportunity',
    label: 'Weekly SEO traffic-opportunity report',
    description: 'Create a weekly organic traffic opportunity report.',
    trigger: 'schedule.weekly',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.weekly-traffic-opportunity',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Scheduled SEO',
    output: 'Weekly SEO report',
  },
  {
    key: 'seo.missingPagesDetector',
    label: 'Missing pages detector',
    description: 'Identify missing fighter, wrestler, event, contest, or landing pages from supplied site inventory.',
    trigger: 'schedule.daily',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.missing-pages-detector',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO quality',
    output: 'Missing pages report',
  },
  {
    key: 'seo.lowQualityPageDetector',
    label: 'Low-quality page detector',
    description: 'Detect thin or weak pages from supplied page inventory.',
    trigger: 'schedule.daily',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.low-quality-page-detector',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO quality',
    output: 'Low-quality page report',
  },
  {
    key: 'seo.brokenInternalLinks',
    label: 'Broken internal link detector',
    description: 'Report broken internal links from crawled or backend-provided URL inventory.',
    trigger: 'schedule.daily',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.broken-link-detector',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO quality',
    output: 'Broken-link report',
  },
  {
    key: 'seo.missingMetadata',
    label: 'Missing meta title/description detector',
    description: 'Detect pages missing useful metadata.',
    trigger: 'schedule.daily',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.missing-meta-detector',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO quality',
    output: 'Metadata gap report',
  },
  {
    key: 'seo.duplicateContentDetector',
    label: 'Duplicate content detector',
    description: 'Find likely duplicate or overlapping pages from supplied inventory.',
    trigger: 'schedule.weekly',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.duplicate-content-detector',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO quality',
    output: 'Duplicate-content report',
  },
  {
    key: 'seo.keywordOpportunityFinder',
    label: 'Keyword opportunity finder',
    description: 'Generate keyword opportunities from supplied events, athletes, pages, and content gaps.',
    trigger: 'schedule.weekly',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.keyword-opportunity',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO growth',
    output: 'Keyword opportunity report',
  },
  {
    key: 'trends.mmaTopicFinder',
    label: 'Trending MMA topic finder',
    description: 'Suggest MMA content topics from supplied data and configured source snapshots.',
    trigger: 'schedule.daily',
    category: 'data',
    vertical: 'combat',
    jobType: 'data.trending-mma-topics',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Trend discovery',
    output: 'MMA topic report',
  },
  {
    key: 'trends.wrestlingTopicFinder',
    label: 'Trending pro-wrestling topic finder',
    description: 'Suggest pro-wrestling content topics from supplied data and configured source snapshots.',
    trigger: 'schedule.daily',
    category: 'data',
    vertical: 'pro_wrestling',
    jobType: 'data.trending-wrestling-topics',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Trend discovery',
    output: 'Wrestling topic report',
  },
  {
    key: 'calendar.contentCalendar',
    label: 'Auto content calendar',
    description: 'Generate a content calendar for blogs, event pages, profiles, and evergreen traffic pages.',
    trigger: 'schedule.weekly',
    category: 'content',
    vertical: 'both',
    jobType: 'content.calendar',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Content planning',
    output: 'Content calendar plan',
  },
  {
    key: 'calendar.blogTopicSuggestions',
    label: 'Auto blog topic suggestions',
    description: 'Generate blog topic ideas for combat and pro-wrestling traffic growth.',
    trigger: 'schedule.daily',
    category: 'content',
    vertical: 'both',
    jobType: 'content.blog-topic-suggestions',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Content planning',
    output: 'Blog topic suggestions',
  },
  {
    key: 'calendar.socialCalendar',
    label: 'Auto social content calendar',
    description: 'Generate a platform-specific social content calendar.',
    trigger: 'schedule.weekly',
    category: 'social',
    vertical: 'both',
    jobType: 'social.calendar',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Content planning',
    output: 'Social content calendar',
  },
  {
    key: 'queue.autoDraftGeneration',
    label: 'Auto draft queue generation',
    description: 'Create a queue of recommended draft jobs from supplied events, athletes, and content gaps.',
    trigger: 'schedule.daily',
    category: 'admin',
    vertical: 'both',
    jobType: 'automation.draft-queue-generation',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Automation control',
    output: 'Draft queue plan',
  },
  {
    key: 'admin.settingsPanel',
    label: 'Admin automation settings panel',
    description: 'Expose automation settings metadata for backend/frontend admin panels.',
    trigger: 'manual.admin',
    category: 'admin',
    vertical: 'both',
    jobType: 'automation.settings-export',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: true,
    requiresApproval: false,
    supportsAutoMode: false,
    riskLevel: 'low',
    adminGroup: 'Automation control',
    output: 'Settings export',
  },
  {
    key: 'admin.promptManagement',
    label: 'Prompt management panel',
    description: 'Expose prompt metadata and version recommendations for admin review.',
    trigger: 'manual.admin',
    category: 'admin',
    vertical: 'both',
    jobType: 'automation.prompt-management',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: true,
    requiresApproval: false,
    supportsAutoMode: false,
    riskLevel: 'low',
    adminGroup: 'Automation control',
    output: 'Prompt management export',
  },
  {
    key: 'ops.failedJobRetry',
    label: 'Failed job retry system',
    description: 'Review failed jobs and recommend safe retry actions.',
    trigger: 'schedule.hourly',
    category: 'admin',
    vertical: 'both',
    jobType: 'automation.failed-job-retry-plan',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: false,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Operations',
    output: 'Failed-job retry plan',
  },
  {
    key: 'analytics.agentPerformance',
    label: 'Agent performance dashboard',
    description: 'Generate agent performance summaries from run logs.',
    trigger: 'schedule.daily',
    category: 'analytics',
    vertical: 'both',
    jobType: 'analytics.agent-performance',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: false,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Analytics',
    output: 'Agent performance report',
  },
  {
    key: 'analytics.trafficGrowthDashboard',
    label: 'Traffic growth dashboard',
    description: 'Create a traffic growth summary from configured analytics inputs.',
    trigger: 'schedule.weekly',
    category: 'analytics',
    vertical: 'both',
    jobType: 'analytics.traffic-growth-dashboard',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: false,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Analytics',
    output: 'Traffic growth report',
  },
  {
    key: 'freshness.contentMonitor',
    label: 'Content freshness monitor',
    description: 'Find old or stale content and recommend updates.',
    trigger: 'schedule.weekly',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.content-freshness-monitor',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Content freshness',
    output: 'Freshness report',
  },
  {
    key: 'freshness.oldBlogUpdateSuggestions',
    label: 'Old blog update suggestions',
    description: 'Recommend updates to older blogs.',
    trigger: 'blog.stale.detected',
    category: 'content',
    vertical: 'both',
    jobType: 'content.old-blog-update-suggestion',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Content freshness',
    output: 'Old blog update suggestion',
  },
  {
    key: 'freshness.autoRefreshOutdatedBlogs',
    label: 'Auto refresh outdated blogs',
    description: 'Create refreshed blog drafts for old content.',
    trigger: 'blog.stale.detected',
    category: 'content',
    vertical: 'both',
    jobType: 'content.old-blog-refresh',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Content freshness',
    output: 'Refreshed blog draft',
  },
  {
    key: 'evergreen.faqGeneration',
    label: 'Auto FAQ generation',
    description: 'Generate FAQ content suggestions for relevant pages.',
    trigger: 'manual.content',
    category: 'content',
    vertical: 'both',
    jobType: 'content.faq',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Evergreen content',
    output: 'FAQ draft',
  },
  {
    key: 'evergreen.howToPlaySuggestions',
    label: 'Auto how-to-play content suggestions',
    description: 'Generate how-to-play content suggestions without changing official rules.',
    trigger: 'manual.content',
    category: 'content',
    vertical: 'both',
    jobType: 'content.how-to-play',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Evergreen content',
    output: 'How-to-play draft',
  },
  {
    key: 'evergreen.landingPageSuggestions',
    label: 'Auto landing page suggestions',
    description: 'Suggest new landing pages for traffic opportunities.',
    trigger: 'manual.content',
    category: 'content',
    vertical: 'both',
    jobType: 'content.landing-page-suggestion',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Evergreen content',
    output: 'Landing page suggestion',
  },
  {
    key: 'seo.canonicalChecks',
    label: 'Auto canonical URL checks',
    description: 'Check canonical URL strategy from supplied page inventory.',
    trigger: 'schedule.weekly',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.canonical-checks',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Technical SEO',
    output: 'Canonical URL report',
  },
  {
    key: 'seo.openGraphTwitterCards',
    label: 'Auto OpenGraph/Twitter card generation',
    description: 'Generate OG and Twitter card metadata recommendations.',
    trigger: 'manual.seo',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.opengraph-twitter-cards',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Technical SEO',
    output: 'OpenGraph/Twitter card package',
  },
  {
    key: 'seo.fightEventStructuredData',
    label: 'Auto fight/event structured data',
    description: 'Generate structured data for combat events and fight pages.',
    trigger: 'manual.seo',
    category: 'seo',
    vertical: 'combat',
    jobType: 'seo.fight-event-structured-data',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Structured data',
    output: 'Fight/event schema package',
  },
  {
    key: 'seo.fighterWrestlerStructuredData',
    label: 'Auto wrestler/fighter structured data',
    description: 'Generate structured data for fighter and wrestler profile pages.',
    trigger: 'manual.seo',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.fighter-wrestler-structured-data',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'Structured data',
    output: 'Profile schema package',
  },
  {
    key: 'social.youtubeCaptionDrafts',
    label: 'Auto YouTube/social caption drafts',
    description: 'Generate caption drafts for YouTube Shorts, community posts, and social media.',
    trigger: 'manual.social',
    category: 'social',
    vertical: 'both',
    jobType: 'social.youtube-caption-draft',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Social channels',
    output: 'Caption draft artifact',
  },
  {
    key: 'social.discordAnnouncements',
    label: 'Auto Discord announcement drafts',
    description: 'Generate Discord announcement drafts for events, contests, and blog content.',
    trigger: 'manual.social',
    category: 'social',
    vertical: 'both',
    jobType: 'social.discord-announcement-draft',
    defaultMode: 'APPROVAL_REQUIRED',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'high',
    adminGroup: 'Social channels',
    output: 'Discord announcement draft',
  },
  {
    key: 'notifications.trafficIssues',
    label: 'Auto admin notifications for traffic issues',
    description: 'Create admin notification drafts when traffic or SEO issue reports find material problems.',
    trigger: 'seo.issue.detected',
    category: 'notification',
    vertical: 'both',
    jobType: 'notification.traffic-issues',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: false,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Notifications',
    output: 'Admin notification draft',
  },
  {
    key: 'notifications.failedAutomations',
    label: 'Auto admin notifications for failed automations',
    description: 'Create admin notifications when important automation jobs fail.',
    trigger: 'automation.failed',
    category: 'notification',
    vertical: 'both',
    jobType: 'notification.failed-automations',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: false,
    supportsAutoMode: true,
    riskLevel: 'low',
    adminGroup: 'Notifications',
    output: 'Failure notification draft',
  },
  {
    key: 'seo.competitorContentGap',
    label: 'Auto competitor/content gap report',
    description: 'Create a content gap report from supplied competitor/topic inputs.',
    trigger: 'schedule.weekly',
    category: 'seo',
    vertical: 'both',
    jobType: 'seo.competitor-gap-report',
    defaultMode: 'DRAFT_ONLY',
    enabledByDefault: false,
    requiresApproval: true,
    supportsAutoMode: true,
    riskLevel: 'medium',
    adminGroup: 'SEO growth',
    output: 'Competitor gap report',
  },
];

export function automationByKey(key: string): AutomationDefinition | undefined {
  return AUTOMATION_DEFINITIONS.find((definition) => definition.key === key);
}

export function automationsByTrigger(trigger: string): AutomationDefinition[] {
  return AUTOMATION_DEFINITIONS.filter((definition) => definition.trigger === trigger);
}

export function automationJobTypes(): JobType[] {
  return [...new Set(AUTOMATION_DEFINITIONS.map((definition) => definition.jobType))] as JobType[];
}
