import { z } from 'zod';
import { requestedBySchema, sourceEntitySchema, swarmModeSchema, verticalSchema } from './domain.js';

export const jobStatusSchema = z.enum([
  'queued',
  'running',
  'retry_pending',
  'awaiting_review',
  'approved',
  'published',
  'rejected',
  'succeeded',
  'failed',
  'dead_letter',
  'cancelled',
]);
export type JobStatus = z.infer<typeof jobStatusSchema>;

export const jobTypeValues = [
  'content.article',
  'content.match-preview',
  'content.event-recap',
  'seo.audit',
  'social.draft',
  'data.external-candidate',
  'wrestling.scorecard-suggestion',
  'wrestling.match-analysis',
  'wrestling.wrestler-profile',
  'system.health-check',
  'content.fight-publish-blog-draft',
  'social.fight-publish-post',
  'seo.metadata',
  'seo.schema-markup',
  'seo.sitemap-refresh',
  'seo.internal-links',
  'content.newsletter-draft',
  'content.fight-result-recap',
  'social.result-post',
  'analytics.leaderboard-summary',
  'content.upcoming-event-preview',
  'content.fight-card-article',
  'social.event-promotional-posts',
  'content.homepage-feature',
  'content.fighter-profile',
  'seo.fighter-refresh',
  'content.fighter-update-suggestion',
  'content.pro-wrestling-match-preview',
  'content.pro-wrestling-result-recap',
  'content.wrestler-profile',
  'content.contest-rules-explainer',
  'social.contest-reminder',
  'social.winners-announcement',
  'social.blog-approved-post',
  'seo.blog-audit',
  'seo.related-post-linking',
  'media.image-prompt',
  'content.blog-newsletter-draft',
  'seo.daily-audit',
  'seo.weekly-traffic-opportunity',
  'seo.missing-pages-detector',
  'seo.low-quality-page-detector',
  'seo.broken-link-detector',
  'seo.missing-meta-detector',
  'seo.duplicate-content-detector',
  'seo.keyword-opportunity',
  'data.trending-mma-topics',
  'data.trending-wrestling-topics',
  'content.calendar',
  'content.blog-topic-suggestions',
  'social.calendar',
  'automation.draft-queue-generation',
  'automation.settings-export',
  'automation.prompt-management',
  'automation.failed-job-retry-plan',
  'analytics.agent-performance',
  'analytics.traffic-growth-dashboard',
  'seo.content-freshness-monitor',
  'content.old-blog-update-suggestion',
  'content.old-blog-refresh',
  'content.faq',
  'content.how-to-play',
  'content.landing-page-suggestion',
  'seo.canonical-checks',
  'seo.opengraph-twitter-cards',
  'seo.fight-event-structured-data',
  'seo.fighter-wrestler-structured-data',
  'social.youtube-caption-draft',
  'social.discord-announcement-draft',
  'notification.traffic-issues',
  'notification.failed-automations',
  'social.instagram-post-draft',
  'social.facebook-post-draft',
  'social.multi-platform-daily-posts',
  'data.fight-calendar-refresh',
  'content.user-dashboard-opportunities',
  'analytics.user-growth-1000-plan',
  'seo.competitor-gap-report',
  'seo.technical-foundation-audit',
  'seo.sitemap-robots-audit',
  'seo.pagination-opportunity-report',
  'seo.image-performance-audit',
  'seo.core-web-vitals-plan',
  'seo.landing-page-roadmap',
  'seo.fight-detail-seo-roadmap',
  'seo.fighter-profile-seo-roadmap',
  'seo.blog-architecture-audit',
  'seo.footer-internal-link-audit',
  'seo.conversion-cta-audit',
  'seo.trust-compliance-content-plan',
  'content.sport-landing-page-brief',
  'content.fight-detail-page-brief',
  'content.fighter-profile-page-brief',
  'data.event-calendar-daily-update',
  'content.fight-card-daily-package',
  'content.blog-seo-daily-articles',
  'social.instagram-growth-posts',
  'social.facebook-growth-posts',
  'social.x-growth-posts',
  'social.youtube-growth-video-draft',
  'social.short-form-video-pack',
  'notification.community-retention-daily',
  'analytics.july-10000-signup-growth-plan',
  'media.blog-featured-image-prompt',
  'media.branded-post-image-prompt',
] as const;

export const jobTypeSchema = z.enum(jobTypeValues);
export type JobType = z.infer<typeof jobTypeSchema>;

export const createJobSchema = z.object({
  vertical: verticalSchema,
  jobType: jobTypeSchema,
  mode: swarmModeSchema.default('DRAFT_ONLY'),
  priority: z.coerce.number().int().min(0).max(100).default(50),
  idempotencyKey: z.string().min(8).max(200).optional(),
  requestedBy: requestedBySchema.default({ source: 'backend' }),
  sourceEntity: sourceEntitySchema,
  input: z.record(z.unknown()).default({}),
  callbackUrl: z.string().url().optional(),
  backendCorrelationId: z.string().optional(),
  scheduledAt: z.coerce.date().optional(),
  maxAttempts: z.coerce.number().int().min(1).max(10).optional(),
  metadata: z.record(z.unknown()).default({}),
});
export type CreateJobInput = z.infer<typeof createJobSchema>;

export const listJobsQuerySchema = z.object({
  status: jobStatusSchema.optional(),
  vertical: verticalSchema.optional(),
  jobType: jobTypeSchema.optional(),
  campaignId: z.string().optional(),
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(25),
});
